import dayjs from "dayjs";

export const RULE_PARAMETER_MAP: Record<string, any[]> = {
  string: [],
  boolean: [],
  accepted: [],
  after: [dayjs().format("YYYY-MM-DD")],
  after_or_equal: [dayjs().format("YYYY-MM-DD")],
  alpha: [],
  alpha_dash: [],
  alpha_num: [],
  array: [],
  before: [dayjs().format("YYYY-MM-DD")],
  before_or_equal: [dayjs().format("YYYY-MM-DD")],
  between: [5, 10],
  confirmed: [],
  date: [],
  digits: [4],
  digits_between: [4],
  email: [],
  hex: [],
  in: ["apple", "orange"],
  integer: [],
  max: [15],
  min: [8],
  not_in: ["apple", "orange"],
  numeric: [],
  required: [],
  size: [10],
  url: [],
};
