import { RuleType, ValidationFunction } from "./Types";
import rules from "./Rules";

export const RULE_FUNCTION_MAPS: Record<RuleType, ValidationFunction> = {
  string: rules.required,
  boolean: rules.required,
  accepted: rules.accepted,
  after: rules.required,
  after_or_equal: rules.required,
  alpha: rules.required,
  alpha_dash: rules.required,
  alpha_num: rules.required,
  array: rules.required,
  before: rules.required,
  before_or_equal: rules.required,
  between: rules.required,
  confirmed: rules.required,
  date: rules.required,
  digits: rules.required,
  digits_between: rules.required,
  email: rules.required,
  hex: rules.required,
  in: rules.required,
  integer: rules.required,
  max: rules.required,
  min: rules.min,
  not_in: rules.required,
  numeric: rules.required,
  required: rules.required,
  size: rules.required,
  url: rules.required,
};
