name: Docs
on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: cd docs && pwd && npm install --frozen-lockfile

      - name: Build
        run: cd docs && pwd && npm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: docs/.vitepress/dist
          external_repository: axe-api/axe-api-v1.github.io
          publish_branch: master
